# Generated by Django 5.0.2 on 2024-02-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=20, null=True)),
                ('per_add', models.CharField(max_length=60, null=True)),
                ('press_add', models.CharField(max_length=60, null=True)),
                ('mobile', models.CharField(max_length=14, null=True)),
                ('nid_number', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=18, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
